USE [AdventureWorks_Stage]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [StageControl].[ErpIncremental](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[InsertedDate] [datetime] NOT NULL,
	[SalesHeaderMaxDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Erp_Incremental] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
